modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Flower%20Mimics"
logoFile="icon.png"

[[mods]]
modId="flowermimics"
version="1.9"
displayName="Flower Mimics"
displayURL="https://serilum.com/mod/flower-mimics"
authors="Rick South"
description='''SpookyJam 2023: Be careful around flowers at night.. they might transform into monsters!
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Michael W. S., Shana Gitnick, Sukhmai, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.flowermimics]]
    modId="collective"
    type="required"
    versionRange="[7.71,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.flowermimics]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "flowermimics.mixins.json"